### PR TITLE
modify the TriType

### PR DESCRIPTION
**Pull request by cxl1521**
Please help to review the changes.

### CODE REVIEW

**Review by DevelopnTest — CHANGES_REQUESTED** [review]
The changes look fine. Have to unit testing the code? What is the code coverage?

**Comment by cxl1521** [comment]
I have added more tests and the statement code coverage is 94%.

**Review by DevelopnTest — APPROVED** [review]
it is great ^^

**Comment by cxl1521** [comment]
Thanks for the help.

**Pull request merged**
